//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public Apartment()
        {
            this.OrderedApartments = new HashSet<OrderedApartment>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public bool TypeVip { get; set; }
        public int MaxCapacity { get; set; }
        public int RoomsNumber { get; set; }
        public double Price { get; set; }
        public int FloorId { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual ICollection<OrderedApartment> OrderedApartments { get; set; }
    }
}
