//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildParent
    {
        public int ParentId { get; set; }
        public int ChildId { get; set; }
    
        public virtual Guest Parent { get; set; }
        public virtual Guest Child { get; set; }
    }
}
