//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyRelation
    {
        public int GuestId { get; set; }
        public int RelativeId { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Guest Guest1 { get; set; }
    }
}
