//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public Guest()
        {
            this.OrderedApartments = new HashSet<OrderedApartment>();
            this.Orders = new HashSet<Order>();
            this.ChildParentsParent = new HashSet<ChildParent>();
            this.ChildParentsChild = new HashSet<ChildParent>();
            this.FamilyRelations = new HashSet<FamilyRelation>();
            this.FamilyRelations1 = new HashSet<FamilyRelation>();
        }
    
        public int Id { get; set; }
        public string PassportNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Sex { get; set; }
        public bool StatusVip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public double Discount { get; set; }
    
        public virtual ICollection<OrderedApartment> OrderedApartments { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ChildParent> ChildParentsParent { get; set; }
        public virtual ICollection<ChildParent> ChildParentsChild { get; set; }
        public virtual ICollection<FamilyRelation> FamilyRelations { get; set; }
        public virtual ICollection<FamilyRelation> FamilyRelations1 { get; set; }
    }
}
