//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedApartment
    {
        public int OrderId { get; set; }
        public int ApartmentId { get; set; }
        public int GuestId { get; set; }
        public System.DateTime ActualDepartureDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Apartment Apartment { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
