//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelISService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderedDishes = new HashSet<OrderedDish>();
            this.OrderedApartments = new HashSet<OrderedApartment>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalPrice { get; set; }
        public int UserId { get; set; }
        public int HotelId { get; set; }
        public int GuestId { get; set; }
    
        public virtual ICollection<OrderedDish> OrderedDishes { get; set; }
        public virtual ICollection<OrderedApartment> OrderedApartments { get; set; }
        public virtual User User { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
